[package]
name = "api"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
dotenv = "0.15.0"
env_logger = "0.11.8"
juniper = "0.17.0"
rsmgclient = "2.0.3"
serde = "1.0.228"
serde_derive = "1.0.228"
serde_json = "1.0.145"
